import type { Lang } from '../locales';
const en = {
 health:'Connection health', unknown:'Not reported', disconnected:'Disconnected', unavailable:'Not supported by phone', idle:'Capture stopped', waiting:'No frames received', stalled:'No frame for over 5 seconds', live:'Receiving frames',
 lastFrame:'Last frame received', never:'None this session', control:'Phone input service', ready:'Ready', needsControl:'Enable Lynko in phone Accessibility settings', refresh:'Refresh phone status', healthHint:'Frame times come from received LV1 images, not connection heartbeats. A quiet or locked screen can stop updating without losing the link.',
 trust:'Desktop feature controls', trustHint:'These preferences apply to this desktop UI, not phone permissions or security isolation. Pairing remembers a device; HTTP and WebSocket traffic is not encrypted. Use a trusted network.',
 screen:'Mirror requests & display', input:'Remote keyboard & pointer', clipboard:'Clipboard access', files:'File sending', notifications:'Notification display & replies', audio:'Phone audio playback',
 privacy:'Notification privacy', hidePreview:'Hide title and message', privacyHint:'Filtering happens before local history and Windows toasts. Changes also remove existing local previews; hidden content cannot be restored. The phone may still transmit it.', blockedApps:'Blocked app identifiers', block:'Block app', unblock:'Unblock', appPlaceholder:'Exact app identifier', hidden:'Preview hidden', clear:'Clear local history',
 queued:'Queued', sending:'Sending / awaiting phone', sent:'Sent', failed:'Failed', cancelled:'Cancelled', retry:'Retry', cancel:'Cancel queued', queueHint:'One file at a time. Retry asks the phone again. Active uploads cannot be cancelled here; queued files can. Progress measures bytes read, not phone acknowledgement.', queuePaused:'Queue waits for the original phone and file sending to be enabled.',
 fit:'Fit', fill:'Fill (crop)', zoom:'Zoom', top:'Always on top', stopCapture:'Stop phone capture', captureHint:'Stop ends phone capture; it does not freeze the last image. Restart may require phone consent.',
 animations:'Interface animations', motionHint:'Optional interface effects; system reduced-motion always takes priority.', forgetConfirm:'Forget this paired phone? An active link will disconnect.', confirm:'Forget phone', cancelAction:'Keep phone', disabled:'Disabled by desktop feature controls', error:'Action failed', seconds:'s ago',
 hotkeys:'Global hotkeys', hotkeysHint:'Work even when Lynko is in the background. Ctrl+Shift+L shows or hides the window, Ctrl+Shift+M toggles the mirror. Both are free — pick different ones if they clash with another app.', hotkeyConflict:'Lynko could not claim that hotkey; another app already owns it. Hotkeys stay off until it is free.',
};
const fa: Record<keyof typeof en,string> = {
 health:'سلامت اتصال', unknown:'گزارش نشده', disconnected:'قطع اتصال', unavailable:'گوشی پشتیبانی نمی‌کند', idle:'ضبط متوقف است', waiting:'هنوز فریمی نرسیده', stalled:'بیش از ۵ ثانیه بدون فریم', live:'در حال دریافت فریم',
 lastFrame:'آخرین فریم دریافتی', never:'در این نشست دریافت نشده', control:'سرویس ورودی گوشی', ready:'آماده', needsControl:'Lynko را در تنظیمات دسترس‌پذیری گوشی فعال کنید', refresh:'تازه‌سازی وضعیت گوشی', healthHint:'زمان فریم از تصاویر LV1 دریافتی است، نه پیام اتصال. صفحه ثابت یا قفل‌شده ممکن است بدون قطع اتصال به‌روز نشود.',
 trust:'کنترل قابلیت‌های دسکتاپ', trustHint:'این تنظیمات فقط رابط دسکتاپ را کنترل می‌کنند، نه مجوز گوشی یا مرز امنیتی. جفت‌سازی دستگاه را به خاطر می‌سپارد؛ ترافیک HTTP و WebSocket رمزگذاری نشده است. از شبکه مطمئن استفاده کنید.',
 screen:'درخواست و نمایش آینه', input:'صفحه‌کلید و اشاره‌گر راه دور', clipboard:'دسترسی کلیپ‌بورد', files:'ارسال فایل', notifications:'نمایش اعلان و پاسخ', audio:'پخش صدای گوشی',
 privacy:'حریم خصوصی اعلان', hidePreview:'پنهان کردن عنوان و پیام', privacyHint:'فیلتر پیش از تاریخچه محلی و اعلان ویندوز اعمال می‌شود. تغییرات پیش‌نمایش‌های قبلی را نیز حذف می‌کند؛ محتوای پنهان بازیابی نمی‌شود. گوشی ممکن است همچنان آن را ارسال کند.', blockedApps:'شناسه برنامه‌های مسدود', block:'مسدود کردن', unblock:'رفع مسدودی', appPlaceholder:'شناسه دقیق برنامه', hidden:'پیش‌نمایش پنهان', clear:'پاک کردن تاریخچه محلی',
 queued:'در صف', sending:'ارسال / انتظار تأیید گوشی', sent:'ارسال شد', failed:'ناموفق', cancelled:'لغو شد', retry:'تلاش دوباره', cancel:'لغو از صف', queueHint:'هر بار یک فایل. تلاش دوباره نیازمند تأیید مجدد گوشی است. لغو ارسال فعال در اینجا ممکن نیست؛ فایل صف را می‌توانید لغو کنید. پیشرفت یعنی بایت خوانده‌شده، نه تأیید گوشی.', queuePaused:'صف منتظر همان گوشی و فعال شدن ارسال فایل می‌ماند.',
 fit:'جا دادن', fill:'پر کردن (برش)', zoom:'بزرگ‌نمایی', top:'همیشه روی پنجره‌ها', stopCapture:'توقف ضبط گوشی', captureHint:'توقف، ضبط گوشی را پایان می‌دهد؛ تصویر آخر را ثابت نمی‌کند. شروع دوباره ممکن است نیازمند رضایت گوشی باشد.',
 animations:'پویانمایی رابط', motionHint:'جلوه‌های اختیاری رابط؛ تنظیم کاهش حرکت سیستم همیشه اولویت دارد.', forgetConfirm:'این گوشی فراموش شود؟ اتصال فعال قطع خواهد شد.', confirm:'فراموش کردن گوشی', cancelAction:'نگه داشتن گوشی', disabled:'در کنترل قابلیت‌های دسکتاپ غیرفعال است', error:'عملیات ناموفق', seconds:'ثانیه پیش',
 hotkeys:'کلیدهای سراسری', hotkeysHint:'حتی وقتی لینکو در پس‌زمینه است کار میکند. Ctrl+Shift+L پنجره را نشان یا پنهان میکند و Ctrl+Shift+M آینه را روشن/خاموش میکند.', hotkeyConflict:'Lynko نتوانست آن کلید را بگیرد؛ برنامه دیگری زودتر آن را دارد.',
};
export type EnhancementKey = keyof typeof en;
export const text = (lang:Lang, key:EnhancementKey) => (lang === 'fa' ? fa : en)[key];
